export const ProductAPI = [
    {
        "product_param": "men-clothes",
        "product_data": [{
            "id": 1,
            "title": "bubba Men's Bahura Long Sleeve Shirt",
            "price": "900",
            "features": [
                "66% Rayon, 28% Cotton, 6% Spandex",
                "PERFORMANCE: Crafted with performance in mind, with UV protective, moisture-wicking, and odor absorbent materials",
                "GREEN: Intentionally developed using eco-friendly, sustainable fabrics",
                "FEATURES: Engineered with front, chest zipper pouch for easy and convenient storage.",
                "DESIGNED: Athletic fit with UPF Protection and temperature regulating material."
            ],
            "rating": "4.8",
            "category": "Men's Clothing",
            "image": "https://assets.myntassets.com/h_720,q_90,w_540/v1/assets/images/12915300/2020/12/3/50df568a-40c1-48d7-83e9-d932cfbcddb11606996093814-INVICTUS-Men-Charcoal-Grey-Solid-Single-Breasted-Slim-Fit-Sm-1.jpg",
            "qty": 1
        },
        {
            "id": 2,
            "title": "YHA Men's Regular Fit Casual Check Shirts",
            "price": "648",
            "features": [
                "Care Instructions: Machine Wash",
                "Fit Type: Regular Fit",
                "Fabric: 100% Cotton",
                "Style: Regular",
                "Neck Style: Collar",
                "Pattern: Check",
                "Wash Care: Machine Wash"
            ],
            "rating": "3.7",
            "category": "Men's Clothing",
            "image": "https://m.media-amazon.com/images/I/81iRLcFy--S._UL1500_.jpg",
            "qty": 1
        },
        {
            "id": 3,
            "title": "LookMark Men's Poly Cotton Digital Printed Stitched Half Sleeve Shirt",
            "price": "419",
            "features": [
                "Care Instructions: Hand Wash Only",
                "Stylish Half sleeve Casual Printed Shirts & Party Wear Casual shirts",
                "100% Premium Poly Cottton, Pre Washed for an extremely soft finish and Rich look",
                "Breathable : Truly comfortable and easy to wear in every season it is insulating in winter and breathable in summer.",
                "Modern slim fit ( we have updated our size chart, please refer the size chart for new measurements before ordering)"
            ],
            "rating": "3.3",
            "category": "Men's Clothing",
            "image": "https://m.media-amazon.com/images/I/71cFpnm0b6S._UL1280_.jpg",
            "qty": 1
        },
        {
            "id": 4,
            "title": "Chromozome Men's Cotton Track Pants",
            "price": "549",
            "features": [
                "Fit Type: Slim",
                "Made of blend of 60% cotton and 40% polyester for extended durability and long wearing comfort.",
                "A highly durable zipper in the right side pocket adding to the enhanced functionality of this product.",
                "Bottom welt are made up from high quality stretch rib fabric for excellent grip.",
                "Reverse & Machine wash 40° C, Tumble dry Medium, Do not IRON on print/Embroidery, wash dark color separately. Made in India.",
                "Two toned fabric that makes this garment very trendy. The style is enhanced with a bright 'C' embroidery on LHS."
            ],
            "rating": "4.0",
            "category": "Men's Clothing",
            "image": "https://m.media-amazon.com/images/I/71X7rpjnxnL._UL1500_.jpg",
            "qty": 1
        },
        {
            "id": 5,
            "title": "Novarc Men's Slim Fit Jeans",
            "price": "640",
            "features": [
                "Care Instructions: Wash dark colors separately",
                "Fit Type: Slim Fit",
                "Fabric: Cotton; Lycra",
                "Style: Jeans ;Pattern: Solid",
                "Rise: Mid Rise ;Closure: Button ;Length: Full Length",
                "Occasion: Casual",
                "Stretch: Stretchable"
            ],
            "rating": "3.6",
            "category": "Men's Clothing",
            "image": "https://m.media-amazon.com/images/I/712pHoSq6WL._UL1500_.jpg",
            "qty": 1
        },
        {
            "id": 6,
            "title": "Chromozome Men's Cotton Shorts",
            "price": "299",
            "features": [
                "STYLE : S 4803 Fit Type: Comfort Fit Chromozome Men's Athletic Shorts",
                "Made from 100% Premium Cotton. All Melanges are made with Cotton Rich Fabric.",
                "This style has a contrast piping on the sides . The side pockets add to the convenience of this style .",
                "Perfect for lounging , running or wearing to the gym - available in a variety of colours"
            ],
            "rating": "3.9",
            "category": "Men's Clothing",
            "image": "https://m.media-amazon.com/images/I/71mAmTZYjKL._UL1500_.jpg",
            "qty": 1
        },
        {
            "id": 7,
            "title": "Shaftesbury London Men's Notch Lapel Slim Blazer",
            "price": "2,789",
            "features": [
                "Care Instructions: Machine Wash",
                "Fit Type: Slim",
                "Color: Blue",
                "Material: Cotton",
                "Long sleeve",
                "Slim fit",
                "Notch collar",
                "Machine wash",
                "Made in India"
            ],
            "rating": "4.6",
            "category": "Men's Clothing",
            "image": "https://m.media-amazon.com/images/I/61p-jdpKGcL._UL1440_.jpg",
            "qty": 1
        },
        {
            "id": 8,
            "title": "ShopyBucket Men's Slim Fit 3 pcs Suit (Coat, Pant & Waistcoat)",
            "price": "4,999",
            "features": [
                "Care Instructions: Dry Clean Only",
                "WASH CARE-Cleaning: Hand Wash is avaliable; Storage: Always hang on; Pressing: Steam ironing.",
                "GREAT VALUE -The prefect and comfortable suit doesn't cost hundreds of dollars to buy. It's a very affordable price, but it's not cheap. The suit is a great choice, it not only suitable for many occaions, but also shows men's charm. That looks as good as more expensive suits. You worth to own it.",
                "SLIM FIT-This suit with full shoulder design and slim cut with 3D draping. Slim fit suits little tighter than a regular fit suit. When you put on it make you slimmer and sharp. And looks modern and handsome.",
                "VERSATILE OCCASION-It's suitable for multi-occasions,like wedding, daily life, business meeting, any fashion forward parties, any grandly holiday and ect. It is also prefect for the young men prepare for the Homingcoming and back to school"
            ],
            "rating": "4.8",
            "category": "Men's Clothing",
            "image": "https://m.media-amazon.com/images/I/41tz5vqMV9L._UL1000_.jpg",
            "qty": 1
        },
        {
            "id": 9,
            "title": "House of Sensation Coat Pant & Waist Coat for Men Stylish Design Wedding, Daily Life, Business Meeting, Engagement",
            "price": "5,999",
            "features": [
                "Care Instructions: Dry Clean Only",
                "WASH CARE-Cleaning: Hand Wash is avaliable; Storage: Always hang on; Pressing: Steam ironing.",
                "GREAT VALUE -The prefect and comfortable suit doesn't cost hundreds of dollars to buy. It's a very affordable price, but it's not cheap. The suit is a great choice, it not only suitable for many occaions, but also shows men's charm. That looks as good as more expensive suits. You worth to own it.",
                "SLIM FIT-This suit with full shoulder design and slim cut with 3D draping. Slim fit suits little tighter than a regular fit suit. When you put on it make you slimmer and sharp. And looks modern and handsome.",
                "VERSATILE OCCASION-It's suitable for multi-occasions,like wedding, daily life, business meeting, any fashion forward parties, any grandly holiday and ect. It is also prefect for the young men prepare for the Homingcoming and back to school"
            ],
            "rating": "4.2",
            "category": "Men's Clothing",
            "image": "https://m.media-amazon.com/images/I/51HfBm-mpNL._UL1280_.jpg",
            "qty": 1
        },
        {
            "id": 10,
            "title": "Urbano Fashion Men's Regular Fit Washed Full Sleeve Denim Jacket",
            "price": "999",
            "features": [
                "Care Instructions: Machine Wash",
                "Fit Type: Regular Fit",
                "2 Dummy Chest Pockets With Flap And 2 Front Welt Pockets ; Regular Length ; Buttoned Cuff",
                "Perfect For Winter Season, Cool Casual, Evening & Holiday Wear",
                "Wash Care - Mild Wash ; Wash Dark Colors Separately ; Disclaimer - There May Be Slight Variation In Shade And Colour Due To Photographic Effects And Monitor Settings"
            ],
            "rating": "4.1",
            "category": "Men's Clothing",
            "image": "https://m.media-amazon.com/images/I/61-LA0Q4BaL._UL1500_.jpg",
            "qty": 1
        }]
    },

    {
        "product_param": "tv",
        "product_data": [{
            "id": 11,
            "title": "AmazonBasics 108cm (43 inch) 4K Ultra HD Smart LED Fire TV AB43U20PS (Black)",
            "price": "27,499",
            "features": [
                "Resolution: 4K Ultra HD (3840 x 2160) | Refresh Rate: 60 hertz | 178° wide viewing angle",
                "Connectivity: 3 HDMI 2.0 ports to connect set top box, Blu Ray players, gaming console | 1 USB 3.0 and 1 USB 2.0 ports to connect hard drives and other USB devices | IR Port to control connected devices like Soundbars, Receivers and Set top boxes",
                "Sound output: Inbuilt 20 Watts Powerful Speakers | Dolby Atmos",
                " Display: A+ Grade LED panel | Dolby vision | HDR 10 + HLG | Amlogic 9th Generation Imaging Engine | Ultra bright screen | Advance picture processing | Anti-aliasing | Dynamic contrast | Dynamic backlight",
                "Warranty Information: 1 Year Comprehensive Warranty and 2 years warranty on panel for malfunction arising from manufacturing defects",
                "Made in India"
            ],
            "rating": "4.2",
            "category": "TV",
            "image": "https://m.media-amazon.com/images/I/61bXjE5ESwS._SL1240_.jpg",
            "qty": 1
        },
        {
            "id": 12,
            "title": "Mi 80 cm (32 inches) HD Ready Android Smart LED TV 4A PRO | L32M5-AL (Black)",
            "price": "15,999",
            "features": [
                "Resolution: HD Ready Android TV (1366x768) | Refresh Rate: 60 hertz",
                "Connectivity: 3 HDMI ports to connect set top box, Blu Ray players, gaming console | 2 USB ports to connect hard drives and other USB devices",
                "Sound: 20 Watts Output | Dolby+ DTS-HD",
                "Smart TV Features : Built-In Wi-Fi | PatchWall | Netflix | Prime Video | Disney+Hotstar and more | Android TV 9.0 | Google Assistant",
                "Display : LED Panel | Vivid Picture engine",
                "Warranty Information: 1 year warranty on product and 1 year extra on Panel"
            ],
            "rating": "4.4",
            "category": "TV",
            "image": "https://m.media-amazon.com/images/I/71Z+l05eSIS._AC_UY218_.jpg",
            "qty": 1
        },
        {
            "id": 13,
            "title": "Mi 108 cm (43 Inches) 4K Ultra HD Android Smart LED TV 4X|L43M4-4AIN (Black)",
            "price": "28,999",
            "features": [
                "Resolution: 4K Ultra HD (3840x2160) | Refresh Rate: 60 hertz",
                "Connectivity: 3 HDMI ports to connect set top box, Blu-ray speakers or a gaming console | 2 USB ports to connect hard drives or other USB devices | 3.5mm Jack to connect your Audio devices | 1 LAN port",
                "Sound: 20 Watts Output | Dolby Audio + DTS-HD",
                "Display : LED Panel | Vivid picture engine | 4K HDR 10', 'Smart TV features : Built-In Wi-Fi | PatchWall | Netflix | Prime Video | Disney+Hotstar and more | Android TV 9.0 | Google Assistant | PatchWall - 25+ Content Partners|Kids Mode with Parental Lock| Smart Recommendations |Universal search| Language Universe | User Centre",
                "Warranty Information: 1 Year Warranty on TV, 2 Years on Panel"
            ],
            "rating": "4.3",
            "category": "TV",
            "image": "https://m.media-amazon.com/images/I/612oGaxp3DS._AC_UY218_.jpg",
            "qty": 1
        },
        {
            "id": 14,
            "title": "Samsung 80 cm (32 inches) Wondertainment Series HD Ready LED Smart TV UA32TE40AAKBXL (Titan Gray) (2020 Model)",
            "price": "18,490",
            "features": [
                "Resolution: HD Ready (1366x768) | Refresh Rate: 60 hertz",
                "Connectivity: 2 HDMI ports to connect set top box, Blu Ray players, gaming console | 1 USB ports to connect hard drives and other USB devices",
                "Sound : 20 Watts Output | Dolby Digital Plus",
                "Smart TV Features : Voice Assistants | SmartThings App | Personal Computer | Home Cloud | Live Cast | Screen Share | Music System |Alexa Built-in: Voice control your TV and your day. Just ask Alexa to search for movies, play music, control smart home devices, get sports updates and more",
                "Display : LED Panel | Mega Contrast | PurColor | HD Picture Quality | Slim & Stylish Design",
                "Warranty Information: 1 year comprehensive warranty plus additional 1 years on panel by brand from date of invoice"
            ],
            "rating": "4.6",
            "category": "TV",
            "image": "https://m.media-amazon.com/images/I/81N8UlFd0kL._SL1500_.jpg",
            "qty": 1
        },
        {
            "id": 15,
            "title": "Samsung 138 cm (55 inches) Crystal 4K Series Ultra HD Smart LED TV UA55AUE60AKLXL (Black) (2021 Model)",
            "price": "52,990",
            "features": [
                "Resolution : Crystal 4K UHD (3840 x 2160) resolution | Refresh Rate : 60 Hertz",
                "Connectivity: 3 HDMI ports to connect set top box, Blu-ray speakers or a gaming console | 1 USB ports to connect hard drives or other USB devices",
                "Display: Ultra HD (4k) LED Panel | One Billion Colors | Air Slim Design | Supports HDR 10+ | PurColor | Mega Contarst | UHD Dimming | Auto Game Mode",
                "Sound: 20 Watts Output | Powerful Speakers with Dolby Digital Plus | Q Symphony",
                "Smart TV Features : Prime Video, Hotstar, Netflix, Zee5 and more | Tap View | PC Mode | Universal Guide | Web Browser | Screen Mirroring",
                "Warranty Information: 1 Year warranty provided by manufacturer from date of purchase and 1 Year Additional on Panel"
            ],
            "rating": "4.2",
            "category": "TV",
            "image": "https://m.media-amazon.com/images/I/917QAUQorDL._SL1500_.jpg",
            "qty": 1
        },
        {
            "id": 16,
            "title": "Samsung 189 cm (75 Inches) 4K Ultra HD Smart QLED TV QA75Q80RAKXXL (Black) (2019 Model)",
            "price": "3,79,990",
            "features": [
                "Resolution: 4K Ultra HD (3840x2160) | Refresh Rate: 120 hertz",
                "Connectivity: 4 HDMI ports to connect set top box, Blu Ray players, gaming console | 3 USB ports to connect hard drives and other USB devices",
                "Sound : 40 Watts Output",
                "Smart TV Features : Smart TV with free apps",
                "Display : QLED | LED Panel | Slim and stylish design",
                "Warranty Information: 1 year 1 Year Comprehensive + 1 Year Additional on Panel by Samsung from date of purchase"
            ],
            "rating": "4.8",
            "category": "TV",
            "image": "https://m.media-amazon.com/images/I/81Pp+KXbrjL._SL1500_.jpg",
            "qty": 1
        },
        {
            "id": 17,
            "title": "Sony Bravia 80 cm (32 inches) HD Ready Smart LED TV 32W6103 (Black) (2021 Model)",
            "price": "26,990",
            "features": [
                "Resolution: HD Ready (1366x768) | Refresh Rate: 60 hertz",
                "Connectivity: 2 HDMI ports to connect set top box, Blu Ray players, gaming console | 2 USB ports to connect hard drives and other USB devices",
                "Sound : 20 Watts Output | Open Baffle Speaker | ClearAudio+ technology | TV MusicBox",
                "Smart TV Features: Amazon Prime Video | Smart TV | Screen Mirroring | Netflix | HDR Gaming",
                "Display: HDR | X-Reality Pro | Motionflow XR 100",
                "Warranty Information: 1 Year warranty provided by Sony from date of purchase"
            ],
            "rating": "4.6",
            "category": "TV",
            "image": "https://m.media-amazon.com/images/I/915X01--m2S._SL1500_.jpg",
            "qty": 1
        },
        {
            "id": 18,
            "title": "Sony Bravia 139 cm (55 inches) 4K Ultra HD Smart LED Google TV KD-55X80AJ (Black) (2021 Model) | with Alexa Compatibility",
            "price": "78,990",
            "features": ["Resolution: 4K Ultra HD (3840 x 2160) | Refresh Rate: 60 hertz", "Connectivity: 4 HDMI ports to connect set top box, Blu Ray players, gaming console | 2 USB ports to connect hard drives and other USB devices", "Sound : 20 Watts Output | X-Balanced Speaker| Bass Reflex speakers | Dolby Atmos | Ambient Optimization", "Smart TV Features: Google TV | Voice Search | Google Play | Chromecast | Netflix | Amazon Prime Video | HDR Gaming | Additional Features: Apple Airplay | Apple Homekit |Alexa", "Display: X1 | 4K HDR | Triluminos pro Display | 4K X-Reality Pro | Motionflow XR100", "Warranty Information: 1 Year warranty provided by Sony from date of purchase"],
            "rating": "4.8",
            "category": "TV",
            "image": "https://m.media-amazon.com/images/I/81t9bFDmxBS._SL1500_.jpg",
            "qty": 1
        },
        {
            "id": 19,
            "title": "Sony Bravia 108 cm (43 inches) 4K Ultra HD Smart Android LED TV KD-43X74 (Black) (2021 Model) | with Alexa Compatibility",
            "price": "55,990",
            "features": ["Resolution: 4K Ultra HD (3840 x 2160) | Refresh Rate: 60 hertz", "Connectivity: 3 HDMI ports to connect set top box, Blu Ray players, gaming console | 2 USB ports to connect hard drives and other USB devices", "Sound : 20 Watts Output | Bass Reflex speakers | Dolby Audio", "Smart TV Features: Android TV | Voice Search | Google Play | Chromecast | Netflix | Amazon Prime Video | HDR Gaming | Additional Features: Alexa", "Display: X1 | 4K HDR | Live Colour Display | 4K X-Reality Pro | Motionflow XR100", "Warranty Information: 1 Year warranty provided by Sony from date of purchase"],
            "rating": "4.7",
            "category": "TV",
            "image": "https://m.media-amazon.com/images/I/71dNEyhrQgS._SL1500_.jpg",
            "qty": 1
        },
        {
            "id": 20,
            "title": "OnePlus 80 cm (32 inches) Y Series HD Ready LED Smart Android TV 32Y1 (Black) (2020 Model)",
            "price": "17,990",
            "features": ["Resolution: HD Ready (1366x768) | Refresh Rate: 60 hertz", "Connectivity: 2 HDMI ports to connect set top box, Blu Ray players, gaming console | 2 USB ports to connect hard drives and other USB devices", "Sound : 20 Watts Output | Dolby Audio", "Smart TV Features: Android TV 9.0 | OnePlus Connect | Google Assistant | Play Store | Chromecast | Shared Album | Supported Apps : Netflix, YouTube, Prime video | Content Calendar | OxygenPlay", "Display : LED Panel | Noise Reduction | Colour Space Mapping |Dynamic Contrast | Anti-Aliasing | DCI-P3 93% colour gamut | Gamma Engine", "Design: Bezel-less | Screen/Body Ratio = 91.4%", "Warranty Information: 1 year comprehensive warranty and additional 1 year on panel provided by the manufacturer from date of purchase"],
            "rating": "4.1",
            "category": "TV",
            "image": "https://m.media-amazon.com/images/I/81FjmqtQUjL._SL1500_.jpg",
            "qty": 1
        }]
    },
    {
        "product_param": "mobiles",
        "product_data": [{
            "id": 21,
            "title": "realme C25s (Watery Blue,128 GB)  (4 GB RAM)",
            "price": "11, 499",
            "features": ["4 GB RAM | 128 GB ROM | Expandable Upto 256 GB", "16.51 cm (6.5 inch) HD+ Display", "13MP + 2MP + 2MP | 8MP Front Camera", "6000 mAh Battery", "MediaTek Helio G85 Processor"],
            "rating": "4.3",
            "category": "Mobiles",
            "image": "https://rukminim1.flixcart.com/image/416/416/kplisnk0/mobile/8/j/s/c25s-rmx3197-realme-original-imag3smgq7frzezw.jpeg?q=70",
            "qty": 1
        },
        {
            "id": 22,
            "title": "realme Narzo 30 (Racing Silver,64 GB) (4 GB RAM) ",
            "price": "12,499",
            "features": ["4 GB RAM | 64 GB ROM | Expandable Upto 256 GB", "16.51 cm (6.5 inch) Full HD+ Display", "48MP + 2MP + 2MP | 16MP Front Camera", "5000 mAh Battery", "MediaTek Helio G95 Processor", "30W Charger"],
            "rating": "4.4",
            "category": "Mobiles",
            "image": "https://rukminim1.flixcart.com/image/416/416/kq18n0w0/mobile/u/w/b/narzo-30-rmx2156-realme-original-imag45ymfpry9ecq.jpeg?q=70",
            "qty": 1
        },
        {
            "id": 23,
            "title": "realme 8 5G (Supersonic Blue,128 GB) (8 GB RAM) ",
            "price": "16,999",
            "features": ["8 GB RAM | 128 GB ROM | Expandable Upto 1 TB", "16.51 cm (6.5 inch) Full HD+ Display", "48MP + 2MP + 2MP | 16MP Front Camera", "5000 mAh Battery", "MediaTek Dimensity 700 (MT6833) Processor"],
            "rating": "4.3",
            "category": "Mobiles",
            "image": "https://rukminim1.flixcart.com/image/416/416/knrsjgw0/mobile/u/f/w/8-5g-rmx3241-realme-original-imag2d8ett6ukhcs.jpeg?q=70",
            "qty": 1
        },
        {
            "id": 24,
            "title": "vivo Y51A (Crystal Symphony,'128 GB) (8 GB RAM) ",
            "price": "17,990",
            "features": ["8 GB RAM | 128 GB ROM | Expandable Upto 1 TB", "16.71 cm (6.58 inch) Full HD+ Display", "48MP + 8MP + 2MP | 16MP Front Camera", "5000 mAh Li-ion Battery", "Qualcomm Snapdragon 662 Processor"],
            "rating": "4.3",
            "category": "Mobiles",
            "image": "https://rukminim1.flixcart.com/image/416/416/kk1h5e80/mobile/3/7/u/vivo-y51a-v2031-original-imafzh2ud9t3wsm7.jpeg?q=70",
            "qty": 1
        },
        {
            "id": 25,
            "title": "vivo Y72 5G (Slate Gray,128 GB) (8 GB RAM) ",
            "price": "20,990",
            "features": ["8 GB RAM | 128 GB ROM", "16.71 cm (6.58 inch) Full HD+ Display", "48MP + 2MP | 8MP Front Camera", "5000 mAh Battery", "Qualcomm Snapdragon 480 Processor"],
            "rating": "4.4",
            "category": "Mobiles",
            "image": "https://rukminim1.flixcart.com/image/416/416/kr3tj0w0/mobile/m/r/7/y72-5g-v2060-vivo-original-imag4yngeb9dz4fe.jpeg?q=70",
            "qty": 1
        },
        {
            "id": 26,
            "title": "SAMSUNG Galaxy A22 (Black,128 GB) (6 GB RAM) ",
            "price": "18,515",
            "features": ["6 GB RAM | 128 GB ROM | Expandable Upto 1 TB", "16.26 cm (6.4 inch) HD+ Display", "48MP Rear Camera | 13MP Front Camera", "5000 mAh Battery"],
            "rating": "4.8",
            "category": "Mobiles",
            "image": "https://rukminim1.flixcart.com/image/416/416/kqqykcw0/mobile/6/3/t/a22-sm-a22sf-ds-samsung-original-imag4pfdwfpbjguk.jpeg?q=70",
            "qty": 1
        },
        {
            "id": 27,
            "title": "SAMSUNG Galaxy M42 5G (Prism Dot Gray,128 GB) (6 GB RAM) ",
            "price": "21,450",
            "features": ["6 GB RAM | 128 GB ROM | Expandable Upto 1 TB", "16.76 cm (6.6 inch) HD+ Display", "48MP Rear Camera", "5000 mAh Battery", "Qualcomm Snapdragon 750G octa core Processor"],
            "rating": "4.3",
            "category": "Mobiles",
            "image": "https://rukminim1.flixcart.com/image/416/416/koenl3k0/mobile/c/b/r/galaxy-m42-5g-sm-m426bzkgins-samsung-original-imag2vggv8jqgh7s.jpeg?q=70",
            "qty": 1
        },
        {
            "id": 28,
            "title": "SAMSUNG Galaxy F62 (Laser Green,128 GB) (8 GB RAM) ",
            "price": "25,999",
            "features": ["8 GB RAM | 128 GB ROM | Expandable Upto 1 TB", "17.02 cm (6.7 inch) Full HD+ Display", "64MP + 12MP + 5MP + 5MP | 32MP Front Camera", "7000 mAh Lithium-ion Battery", "Exynos 9825 Processor"],
            "rating": "4.3",
            "category": "Mobiles",
            "image": "https://rukminim1.flixcart.com/image/416/416/klb78nk0/mobile/m/2/k/galaxy-f62-sm-e625fzggins-samsung-original-imagygxxse8gbaby.jpeg?q=70",
            "qty": 1
        },
        {
            "id": 29,
            "title": "Mi 10i (Atlantic Blue,128 GB) (6 GB RAM) ",
            "price": "22,165",
            "features": ["6 GB RAM | 128 GB ROM", "16.94 cm (6.67 inch) Display", "108MP Rear Camera | 16MP Front Camera", "4820 mAh Battery"],
            "rating": "4.3",
            "category": "Mobiles",
            "image": "https://rukminim1.flixcart.com/image/416/416/kesv0y80/mobile/w/g/r/mi-redmi-9a-b08696xb4b-original-imafve7pjpemhwk5.jpeg?q=70",
            "qty": 1
        },
        {
            "id": 30,
            "title": "Mi 11 Lite (Jazz Blue, 128 GB) (6 GB RAM) ",
            "price": "21, 999",
            "features": ["6 GB RAM | 128 GB ROM | Expandable Upto 512 GB", "16.64 cm (6.55 inch) Full HD+ Display", "64MP + 8MP + 5MP | 16MP Front Camera", "4250 mAh Li-Polymer Battery", "Qualcomm Snapdragon 732G Processor"],
            "rating": "4.2",
            "category": "Mobiles",
            "image": "https://rukminim1.flixcart.com/image/416/416/kq6yefk0/mobile/i/w/m/11-lite-m2101k9ai-mi-original-imag496gkgqjrvvg.jpeg?q=70",
            "qty": 1
        }]
    },

    {
        "product_param": "men-shoes",
        "product_data": [{
            "id": 31,
            "title": "Adidas Men Running Shoes",
            "price": "1,649",
            "features": ["Closure: Lace-Up", "Shoe Width: Medium", "This product runs a size small. If you usually buy UK 9, buy UK 10 for this", "Material Type: Synthetic", "Lifestyle: Casual", "Closure Type: Lace-Up", "Warranty Type: Manufacturer", "Product warranty against manufacturing defects: 90 days"],
            "rating": "4.2",
            "category": "Men's Shoes",
            "image": "https://m.media-amazon.com/images/I/71TkaXo-VcL._UL1500_.jpg",
            "qty": 1
        },
        {
            "id": 32,
            "title": "Adidas Men's Glenn M Sneakers",
            "price": "2,249",
            "features": ["Sole: Rubber", "Closure: Lace-Up", "Heel Height: 1 inches", "Shoe Width: Regular", "Outer Material: Mesh", "Toe Style: Round Toe", "Closure Type: Lace-Up", "Warranty Type: Manufacturer & Seller", "Warranty Description: 30 days"],
            "rating": "4.0",
            "category": "Men's Shoes",
            "image": "https://m.media-amazon.com/images/I/61N--EbFDZL._UL1000_.jpg",
            "qty": 1
        },
        {
            "id": 33,
            "title": "Puma Zod Runner Idp Men’s Running Shoes",
            "price": "3,125",
            "features": ["Sole: Rubber", "Closure: Speed Laces", "Shoe Width: Medium", "Style Name:-Zod Runner IDP Men’s Running Shoes", "Upper Material:-Textile", "Lower Material:-Rubber", "Care Instructions: Wipe with a clean dry cloth", "Warranty Period: 90 Days Manufacturers Warranty"],
            "rating": "3.7",
            "category": "Men's Shoes",
            "image": "https://m.media-amazon.com/images/I/5199yXGF-QL._UL1200_.jpg",
            "qty": 1
        },
        {
            "id": 34,
            "title": "Puma Men's Slyde Star Slip on Idp Black-Silver Sneaker",
            "price": "1,625",
            "features": ["Sole: Rubber", "Closure: Pull On", "Shoe Width: Medium", "Style Name:-Sneaker", "Model Name:-Slyde Star Slip On IDP CASTLEROCK-High R", "Material Type:-Canvas and Rubber", "Fastening Type:-Slip-On", "Wipe with a clean dry cloth"],
            "rating": "4.1",
            "category": "Men's Shoes",
            "image": "https://m.media-amazon.com/images/I/61JuI4q06CS._UL1200_.jpg",
            "qty": 1
        },
        {
            "id": 35,
            "title": "ASIAN Men's Rider-01 Phylon Sports,Running,Walking Shoes",
            "price": "1,439",
            "features": ["Sole: Synthetic Rubber", "Closure: Lace-Up", "Heel Height: 1.2 inches", "Shoe Width: Medium", "Sole features: height increasing non marking phylon sole made with light weight compound and orthopedic memory foam shoes with beads technology for extra jump which provides extra comfort to your feet with a perfect grip. Features nitro capsule technology for added vacuum based air cushion under your heels", "About ASIAN shoes: we are an ISO 9001: 2015 certified seller of branded footwear online, endorsed by cricketer virender sehwag, with 4/5 overall rating across 11,000 + reviews, offering the latest best quality trending shoes for men"],
            "rating": "3.7",
            "category": "Men's Shoes",
            "image": "https://m.media-amazon.com/images/I/61rOuFqRG6L._UL1100_.jpg",
            "qty": 1
        },
        {
            "id": 36,
            "title": "Puma Men's 19.1 Bowling Cricket Shoe",
            "price": "8,999",
            "features": ["Sole: Rubber", "Closure: Lace-Up", "Shoe Width: Medium", "Model Name:-PUMA 19.1 Bowling", "Style Name:-Cricket Shoe", "Wipe with a clean dry cloth"],
            "rating": "4.7",
            "category": "Men's Shoes",
            "image": "https://m.media-amazon.com/images/I/616TJDofg3L._UL1200_.jpg",
            "qty": 1
        },
        {
            "id": 37,
            "title": "Red Chief Casual Shoes for Men RC3051",
            "price": "4,090",
            "features": ["Material: Leather", "Lifestyle: Casual", "Warranty Type: Manufacturer", "Product Warranty against manufacturing defects: 90 days", "Care Instructions: Clean your shoes with leather cleaner or leather shampoo, and use a good quality brush to remove loose surface dirt; If your shoes are wet after cleaning, let them air-dry before your proceed with the next step; dry shoes in room temperature only and never expose them to the sun; heat from the sun will cause the leather to shrink, wrinkle, harden, dry, and crack"],
            "rating": "4.1",
            "category": "Men's Shoes",
            "image": "https://m.media-amazon.com/images/I/51NVzsOhImL.jpg",
            "qty": 1
        },
        {
            "id": 38,
            "title": "Woodland Men Sneakers",
            "price": "3,895",
            "features": ["Sole: Leather", "Closure: Lace-Up", "Shoe Width: Medium", "Material Type: Leather", "Lifestyle: Casual", "Closure Type: Lace-Up, Cushioned collar, Rust free metal eyelets", "Warranty Type: Manufacturer", "Product warranty against manufacturing defects: 90 days"],
            "rating": "4.4",
            "category": "Men's Shoes",
            "image": "https://m.media-amazon.com/images/I/61DZXfM9rqL._UL1258_.jpg",
            "qty": 1
        },
        {
            "id": 39,
            "title": "Nike' Quest 3-CD0230-016-12, Black Red'",
            "price": "4,616",
            "features": ["Closure: Lace-Up", "Shoe Width: Medium", "Target gender: unisex", "closure type:Lace-Up", "item package dimensions: 330.0 L x 230.0 W x 110.0 H (millimeters)", "item weight: 800.0 grams"],
            "rating": "4.5",
            "category": "Men's Shoes",
            "image": "https://m.media-amazon.com/images/I/61F4Qu2-Z0L._UL1500_.jpg",
            "qty": 1
        },
        {
            "id": 40,
            "title": "Campus Men's Remo Running Shoes",
            "price": "1,699",
            "features": ["Sole: Phylon", "Closure: Lace-Up", "Shoe Width: Medium", "Material Type: Mesh", "Lifestyle: Sports", "Warranty Type: Manufacturer", "Care Instructions: Allow your pair of shoes to air and de-odorize at a regular basis, this also helps them retain their natural shape; use shoe bags to prevent any stains or mildew; dust any dry dirt from the surface using a clean cloth, do not use polish or shiner"],
            "rating": "4.1",
            "category": "Men's Shoes",
            "image": "https://m.media-amazon.com/images/I/71pMZv9Gp2L._UL1500_.jpg",
            "qty": 1
        }]
    },

    {
        "product_param": "cosmetic",
        "product_data": [{
            "id": 41,
            "title": "NIVEA Men Maximum Hydration Moisturizing Face Wash - Helps Prevent Dry Tight Skin - 5 fl. oz. Tube",
            "price": "350",
            "features": ["Deeply cleans skin, removing dirt and excess oils", "Moisturizes while it cleans", "Specially formulated with Aloe Vera and Proviamin B5", "Skin will be thoroughly clean and healthy looking", "Protects skin from drying out"],
            "rating": "4.6",
            "category": "Cosmetic",
            "param": "cosmetic",
            "image": "https://m.media-amazon.com/images/I/71MjQTzoF5L._SL1500_.jpg",
            "qty": 1
        },
        {
            "id": 42,
            "title": "WOW Skin Science Apple Cider Vinegar Foaming Face Wash",
            "price": "370",
            "features": ["Bioacitve-rich with pure Apple Cider Vinegar, Aloe Vera Extract and Vitamins B5 & E", "PREVENTS future breakouts and REDUCES active breakouts using natural NOT chemical ingredients.:Cleansing, healing & hydrating action for clear, soft & supple skin", "Apple Cider Vinegar KILLS bacteria, removes excess dirt oil & makeup and removes dead skin cells.Perfect skin care solution for daily use", "Natural Vitamin E oil REPAIRS damaged skin, heals scars, fades blemishes and eases redness.:No PARABENS, SULPHATE or SILICONES", "Suits all skin types"],
            "rating": "4.1",
            "category": "Cosmetic",
            "param": "cosmetic",
            "image": "https://m.media-amazon.com/images/I/81GpSfq3LzS._SL1500_.jpg",
            "qty": 1
        },
        {
            "id": 43,
            "title": "POND'S Pure Detox Anti Pollution Activated Charcoal Face Wash, 200 g",
            "price": "245",
            "features": ["Anti pollution. Ingredient Type:Non-Organic", "purity", "Activated charcoal", "polution removal", "pollution-free glow", "clears impurities"],
            "rating": "4.4",
            "category": "Cosmetic",
            "param": "cosmetic",
            "image": "https://m.media-amazon.com/images/I/51gP7YWseDL._SL1000_.jpg",
            "qty": 1
        },
        {
            "id": 44,
            "title": "Olay Night Cream Total Effects 7 in 1, Night Cream, 50g",
            "price": "719",
            "features": ["Specially formulated to help fight the 7 Signs of Skin Ageing", "Reduces spots, firms skin, reduces the appearance of lines & wrinkles, smoothens and moisturizes skin, evens skin tone, reduces pores and makes your skin glow", "Formulated with a special complex of VitaNiacin and Anti-Oxidants which together work to fight the 7 Signs of Skin Ageing and give you younger looking skin", "Suitable for Normal to Combination Skin"],
            "rating": "4.2",
            "category": "Cosmetic",
            "param": "cosmetic",
            "image": "https://m.media-amazon.com/images/I/51NeUMoRIIL._SL1200_.jpg",
            "qty": 1
        },
        {
            "id": 45,
            "title": "Fair and Handsome Radiance Cream For Men, 60g",
            "price": "105",
            "features": ["Fair and Handsome is a pioneer and leader in mens fairness category and thus understands mens skin needs the best", "Compared to womens skin, mens skin sweats more, has a top layer that is 20% thicker, secretes more oil, is rough and dry due to regular shaving and looks uneven. There is a need for specialised cream designed specially for mens tough skin", "Fair and Handsome has a powerful pro peptide that helps transform mens tough skin and give radiance from within", "With an advanced formulation the cream gives suoerior oil reduction and radiant skin in just 7 days as compared to womens cream"],
            "rating": "4.2",
            "category": "Cosmetic",
            "param": "cosmetic",
            "image": "https://m.media-amazon.com/images/I/71Aeb6NwdJL._SL1500_.jpg",
            "qty": 1
        },
        {
            "id": 46,
            "title": "Glow & Lovely Advanced Multivitamin Face Cream, 80 g",
            "price": "161",
            "features": ["Glow & Lovely Advanced Multivitamin Face cream, formerly known as Fair & Lovely, is a daily moisturiser that gives you a Radiant Glow - Skin Clarity, Brightness and Radiance", "It’s advanced Multivitamin formula with Vitamins B3, C & E, goes 15 layers deep to brighten skin cells and give you a glow", "Its vanishing cream formula gives you a matte, non oily look, and helps protect glow even under the sun", "Use twice daily after cleansing face for best results", "Dermatologically tested, does not contain any bleaching agents and is safe to use daily", "More from Glow & Lovely- Facewashes, Winter Cream, Ayurvedic care Cream and BB cream"],
            "rating": "4.4",
            "category": "Cosmetic",
            "param": "cosmetic",
            "image": "https://m.media-amazon.com/images/I/51guZJIn4VL._SL1000_.jpg",
            "qty": 1
        },
        {
            "id": 47,
            "title": "Biotique Morning Nectar Flawless Skin moisturizer for All Skin Types, 190ml",
            "price": "182",
            "features": ["Quantity: 190ml; Item Form: Lotion. Ideal Usage : All Day", "Bio Nectar lotion is easily absorbed, replacing the natural oils and moisture the skin loses every day; Its nourishing and hydrating actions provide a pleasant soothing feeling, without leaving any greasy film", "As soon as you apply Morning Nectar you get a feeling of well being and your skin feels soothed and smooth; Morning and evening after the Freshener, smooth-en it over face and neck", "Skin Type: For All Skin Types", "Usage: Apply evenly over cleansed face and neck, morning and evening. Wear alone or under makeup."],
            "rating": "4.3",
            "category": "Cosmetic",
            "param": "cosmetic",
            "image": "https://m.media-amazon.com/images/I/61EOqBT9dDL._SL1200_.jpg",
            "qty": 1
        },
        {
            "id": 48,
            "title": "Lakme Peach Milk Soft Creme Moisturizer, Lightweight Face Cream, Non Sticky, Locks Moisture For 24 Hours For Soft And Glowing Skin, 250 gs",
            "price": "241",
            "features": ["Infused with the goodness of peaches and milk", "This light moisturizer has a soothing fragrance. Dermatologist Tested : Yes", "It easily absorbs into the skin to lock moisture for 24 hours to give you soft, glowing skin", "For intense nourishment - try the lakme peach milk intense lotion", "For nourishment + sun protection - try the lakme peach milk SPF 24 lotion"],
            "rating": "4.4",
            "category": "Cosmetic",
            "param": "cosmetic",
            "image": "https://m.media-amazon.com/images/I/51DDJhaLHtL._SL1000_.jpg",
            "qty": 1
        },
        {
            "id": 49,
            "title": "Vaseline Intensive Care 24 hr nourishing Cocoa Glow Body Lotion with Cocoa And Shea Butter, Restores Glow for all skin type - 400 ml",
            "price": "299",
            "features": ["Vaseline Intensive Care Cocoa Glow Body Lotion moisturizes dry skin from the first application", "Absorbs fast for a non-greasy feel. Ideal For Women.", "Contains 100% pure cocoa and shea butters, known to reveal skin’s natural glow and micro-droplets of Vaseline Jelly to lock in moisture", "Heals dry skin for glowing radiance with rich moisturization", "Daily body lotion best for: dry skin, dull skin, rough skin"
            ],
            "rating": "4.4",
            "category": "Cosmetic",
            "param": "cosmetic",
            "image": "https://m.media-amazon.com/images/I/51H0UkUHduL._SL1000_.jpg",
            "qty": 1
        },
        {
            "id": 50,
            "title": "SkinKraft Dark Spot Control And Skin Renewal Serum",
            "price": "699",
            "features": ["DERMATOLOGIST-VERIFIED SERUM FOR DARK PATCHES: This serum is specially formulated for dark spots, dark patches, and ageing skin. It is effective in controlling the excess production and transfer of melanin in the skin.", "ADVANCED FORMULA FOR STUBBORN DARK SPOTS AND PATCHES: The advanced formula in the serum lightens forms of pigmentation by interfering with the process through which freshly made pigments travel to the surface of the skin.", "VISIBLY FADES DARK SPOTS: It inhibits melanin production in the skin, which lightens hyperpigmentation and brown spots, even out skin tone, and enhances skin radiance over time.", "BACKED BY SCIENCE: All SkinKraft products are designed by Dermato-Cosmetologists, Pharmacists, and Pharmaceutical Engineers. They do not contain Parabens, SLS, Formaldehyde, and Phthalates. The customized serum is 100% safe and effective for your skin."
            ],
            "rating": "3.6",
            "category": "Cosmetic",
            "param": "cosmetic",
            "image": "https://m.media-amazon.com/images/I/51ltJCrx+JL._SL1000_.jpg",
            "qty": 1
        }]
    },

    {
        "product_param": "laptop",
        "product_data": [{
            "id": 51,
            "title": "LG Gram 16 Ultra-Light 11th Gen Core i5,8 GB RAM, 512 GB SSD, Win-10, Iris Xe Graphics, 16-inches (40.64 cms), Thunderbolt 4, USC -C x 2 (with Power), 1.19 kg, 3 Yr Warranty (16Z90P-G.AJ55A2, Black)",
            "price": "1,00,567",
            "features": ["Processor & OS: Intel 11th Gen Corei5-1135G7 (2.4 GHz, Turbo up to 4.2 GHz, L3 Cache   8MB, 28 W)- Window 10",
                "Display: 16inch (40.6 cm) WQXGA (2560 x 1600) 16:10 Aspect Ratio IPS Display with DCI-P3 99%",
                "Memory: 8 GB LPDDR4X (Dual Channel-4266 MHz)",
                "Storage: 512 GB SSD (Type:M.2 2280) NVMe with additional expansion slot",
                "Product & Battery: Weight 1.19 Kg Magnesium Alloy - 80 Wh Battery with 16.5 hr back-up (* MobileMark 2018)"],
            "description": "none",
            "rating": "5.0",
            "category": "electronics",
            "image": "https://m.media-amazon.com/images/I/51IsmTVIDEL._AC_UY218_.jpg",
            "qty": 1
        },
        {
            "id": 52,
            "title": "HP 15 AMD Athlon 15.6inch (39.62cms) HD Laptop (Silver-3050U/4GB/1TB/Win 10/MS Office/Jet Black/1.85kg), 15s-gy0001au",
            "price": "29,632",
            "features": ["Processor: AMD Athlon Silver 3050U (2.3 GHz base clock, up to 3.2 GHz max boost clock, 4 MB L3 cache, 2 cores)",
                "Memory & Storage: 4 GB DDR4 2400 SDRAM (1 x 4 GB) | Storage: 1 TB 5400 rpm SATA HDD",
                "Display: 15.6-inch diagonal, HD (1366 x 768), micro-edge, BrightView, 220 nits, 45% NTSC", "Operating System: Preloaded Windows 10 Home with lifetime validity",
                "Keyboard: Full-size, jet black keyboard with numeric keypad | Precision Touchpad Support | Touchpad with multi-touch gesture support"],
            "description": "none",
            "rating": "3.5",
            "category": "electronics",
            "image": "https://m.media-amazon.com/images/I/61bkuSlKF4L._AC_UY218_.jpg",
            "qty": 1
        },
        {
            "id": 53,
            "title": "HP 15 Intel Pentium Gold 6405U Processor Entry Level 15.6-inch (39.62 cms) FHD Laptop (4GB/1TB/Win 10/Jet Black/1.74kg), 15s-du1052tu",
            "price": "27,990",
            "features": ["Design & Battery: Thin and light design | Laptop weight: 1.74 kg | Average battery life 7 hours, 3-cell, 41 Wh Li-ion Fast Charge Battery",
                "Operating System: Pre-loaded Windows 10 Home with lifetime validity",
                "Graphics: Intel UHD Graphics",
                "Ports: 1 SuperSpeed USB Type-C (5Gbps), 2 SuperSpeed USB Type-A (5Gbps), 1 microSD card reader | Without CD-Drive"],
            "description": "none",
            "rating": "3.4",
            "category": "electronics",
            "image": "https://m.media-amazon.com/images/I/71FB8qoB78L._AC_UY218_.jpg",
            "qty": 1
        },
        {
            "id": 54,
            "title": "HP Pavilion Gaming 10th Gen Intel Core i5 Processor 15.6-inch(39.6 cm) FHD Gaming Laptop (8GB/512GB SSD + 32GB Intel Optane/144 Hz/Win10/MS Office/NVIDIA GTX 1650 4GB/Shadow Black), 15-dk1148TX",
            "price": "66,990",
            "features": ["Processor: 10th Gen Intel Core i5-10300H (2.5 GHz base frequency, up to 4.5 GHz with Intel Turbo Boost Technology, 8 MB L3 cache, 4 cores)",
                "Memory: 8 GB DDR4-2933 SDRAM (1 x 8 GB), upgradable upto 32 GB (2 x 16 GB) | Storage: 512 GB PCIe NVMe M.2 SSD + 32 GB Intel Optane Memory",
                "Display: 15.6-Inch FHD IPS micro-edge, anti-glare Display |Brightness: 250 nits, 141ppi, 45% NTSC (1920 x 1080) | Refresh Rate: 144 Hz",
                "Graphics: NVIDIA GeForce GTX 1650 (4 GB GDDR6 dedicated)",
                "Operating System & Software: Pre-loaded Windows 10 Home with lifetime validity | Pre-installed Microsoft Office Home & Student 2019"],
            "description": "none",
            "rating": "4.4",
            "category": "electronics",
            "image": "https://m.media-amazon.com/images/I/611VHOvjkES._AC_UY218_.jpg",
            "qty": 1
        },
        {
            "id": 55,
            "title": "Acer Extensa 15 Thin & Light Laptop Intel Processor Pentium Silver N5030 15.6 inch (35.56 cms) (4GB RAM/1TB HDD/Windows 10/Integrated Graphic Card/Black/1.9 Kg),EX215-31",
            "price": "28,178",
            "features": ["𝗙𝗮𝘀𝘁 𝗮𝗻𝗱 𝗘𝗮𝘀𝘆 𝗖𝗼𝗺𝗽𝘂𝘁𝗶𝗻𝗴 :Perfect budget laptop under 30000 for students and working professionals that helps get jobs done quickly and efficiently thanks to the Intel Pentium Silver N5030 processor.",
                "𝗥𝗲𝗳𝗶𝗻𝗲𝗱 𝗗𝗲𝘀𝗶𝗴𝗻 𝗮𝗻𝗱 𝗟𝗶𝗴𝗵𝘁 𝗪𝗲𝗶𝗴𝗵𝘁:The latest Extensa Acer Laptop has been redesigned to be thinner and lighter than ever. With less than 20mm thin and with a weight of around 1.9kg, it can accompany you wherever you need to go",
                "𝗘𝗮𝘀𝗲 𝗼𝗳 𝗦𝘁𝗼𝗿𝗮𝗴𝗲: 4 GB RAM Laptop with 1 TB HDD helps easily store and share important projects and data",
                "𝗘𝗻𝗵𝗮𝗻𝗰𝗲𝗱 𝗩𝗶𝗱𝗲𝗼 𝗖𝗼𝗻𝗳𝗲𝗿𝗲𝗻𝗰𝗶𝗻𝗴 𝗮𝗻𝗱 𝗚𝗼𝗼𝗱 𝗕𝗮𝘁𝘁𝗲𝗿𝘆 𝗟𝗶𝗳𝗲: The Extensa 15 will help improve your all-round video conferencing experience. It maintains a strong, consistent wireless signal with the strategically placed Wi-Fi 5 (802.11ac) wireless antenna and MU-MIMO. It also offers battery life upto 6.5 hours.",
                "𝗔𝗱𝗱𝗶𝘁𝗶𝗼𝗻𝗮𝗹 𝗕𝗲𝗻𝗲𝗳𝗶𝘁𝘀 𝗮𝗻𝗱 𝗖𝘂𝘀𝘁𝗼𝗺𝗲𝗿 𝗦𝘂𝗽𝗽𝗼𝗿𝘁 𝗗𝗲𝘁𝗮𝗶𝗹𝘀: The Laptop comes with Windows 10 Home and 1 year International Travellers Warranty.Call 1800-11-6677 to reach out to Acer customer support team for any queries"],
            "description": "none",
            "rating": "3.8",
            "category": "electronics",
            "image": "https://m.media-amazon.com/images/I/816U-xDHnKS._SL1500_.jpg",
            "qty": 1
        },
        {
            "id": 56,
            "title": "Lenovo V15 AMD 15.6-inch (39.6 cm) FHD Thin and Light Laptop (AMD Athlon Silver 3050 U/ 4GB RAM/ 1TB HDD/ Windows 10 Home/Integrated AMD R adeon Graphics/ Iron Grey/ 1.85 kg), 82C700J0IH",
            "price": "29,380",
            "features": ["Commercial Grade Durable Laptop | Secure Laptop (TPM 2.0 - Trusted Platform Module for security) | Spill Resistant Keyboard | 180 degree Metal Alloy Hinges tested for 30000 cycles",
                "Processor: AMD Athlon Silver 3050U processor, base speed 2.3 Ghz, max speed 3.2 Ghz, 2 Cores, 4MB smart cache",
                "Memory: 4GB DDR4 RAM | Storage: 1TB HDD @ 7200RPM | Operating System: Winfows 10 Home | This genuine Lenovo Laptop comes with 1 year onsite warranty",
                "Display: 15-inch screen with (1920 x 1080) FHD display | Anti Glare Technology | Connectivity: 802.11ac 1x1 Wi-Fi + Bluetooth 4.2 | Audio: 1.5W x 2 Dolby Audio Speakers",
                "Design & battery: Thin and Light Laptop | 180 Degree Hinge | Laptop Weight: 1.85 kg | Battery Life: Upto 5.5 Hr as per MobileMark 2014"],
            "description": "none",
            "rating": "3.2",
            "category": "electronics",
            "image": "https://m.media-amazon.com/images/I/71vCx6vbdBL._SL1500_.jpg",
            "qty": 1
        },
        {
            "id": 57,
            "title": "Dell 14 (2021) Thin & Light i3-1005G1 Laptop, 4Gb RAM, 1TB HDD + 256GB SSD, 14” (35.56 Cms) FHD AG Display, Win 10 + MSO, Black (Vostro 3401, D552151WIN9BE)",
            "price": "39,190",
            "features": ["Processor: 10th Generation Intel Core i3-1005G1 Processor (4MB Cache, up to 3.4 GHz)",
                "Memory & Storage:4GB RAM | 256GB M.2 PCIe NVMe Solid State Drive+1TB 5400 rpm 2.5' SATA Hard Drive",
                "Display:14.0-inch FHD (1920 x 1080) Anti-glare LED Backlight Narrow Border WVA Display",
                "Graphics: Intel UHD Graphics with shared graphics memory",
                "Operating System & Software: Windows 10 Home Single Language | Microsoft Office Home and Student 2019",
                "I/O ports: Two USB 3.2 Gen-1,One USB 2.0,One RJ45,One SD card slot ,One HDMI 1.4 port"],
            "description": "none",
            "rating": "4.1",
            "category": "electronics",
            "image": "https://m.media-amazon.com/images/I/8147cwFm2PL._SL1500_.jpg",
            "qty": 1
        },
        {
            "id": 58,
            "title": "MSI GF65 Thin, Intel i7-10750H, 15.6inch FHD (39.6 cm) IPS-Level 144Hz Panel Laptop (16GB/512GB NVMe SSD/Windows 10 Home/Nvidia GTX1660 Ti 6GB GDDR6/Black/1.86Kg), 10SDR-1280IN",
            "price": "81,990",
            "features": ["Processor: 10th Generation Intel Core i7-10750H Up To 5GHz",
                "Operating System: Pre-loaded Windows 10 Home with lifetime validity |Preinstalled Software: MSI BurnRecovery, MSI Battery Calibration, MSI Help Desk, Norton Internet Security (trail 60days) Norton Studio (Metro) (permanent free), Nvidia GeForce Experience, Nahimic 3, Dragon Center | In the box: Laptop, adapter",
                "Display: 15.6inch (39.6 cm) FHD (1920*1080), IPS-Level 144Hz Thin Bezel, 45% NTSC",
                "Memory & Storage: 8GB*2 DDR4 2666MHz RAM, expandable to 64 GB | Storage: 512GB NVMe SSD.",
                "NVIDIA GeForce GTX 1660Ti GDDR6 6GB Dedicated Graphics"],
            "description": "none",
            "rating": "3.8",
            "category": "electronics",
            "image": "https://m.media-amazon.com/images/I/81RJBDd3jyL._SL1500_.jpg",
            "qty": 1
        },
        {
            "id": 59,
            "title": "Lenovo IdeaPad Gaming 3 Intel Core i5 10th Gen 15.6-inch (39.6 cm) FHD 120Hz IPS Gaming Laptop (8GB/1TB HDD +256GB SSD/Windows 10/NVIDIA GTX 1650 4GB GDDR6/Onyx Black/2.2Kg), 81Y4017TIN",
            "price": "60,790",
            "features": ["Processor: 10th Gen Intel Core i5- 10300H | Speed: 2.5 GHz (Base) - 4.5 GHz (Max) | 4 Cores | 8MB Cache",
                "OS: Pre-Loaded Windows 10 Home with Lifetime Validity",
                "Memory and Storage: 8GB RAM DDR4-3200, Upgradable up to 16GB | 256 GB SSD + 1 TB HDD",
                "Graphics: NVIDIA GeForce GTX 1650 4GB GDDR6 Dedicated Graphics",
                "Display: 15.6inch Full HD (1920x1080) | Brightness: 250 nits | Anti-Glare | IPS Technology | 120 Hz Refresh Rate"],
            "description": "none",
            "rating": "4.0",
            "category": "electronics",
            "image": "https://m.media-amazon.com/images/I/61fpo-87DyL._SL1000_.jpg",
            "qty": 1
        },
        {
            "id": 60,
            "title": "Dell Inspiron 3501 15.6inch FHD Display Laptop (i3-1115G4 / 4GB / 256GB SSD / Integrated Graphics / Win10 + MSO / Accent Black) D560492WIN9BE",
            "price": "38,888",
            "features": ["Processor:11th Generation Intel Core i3-1115G4 Processor (6MB Cache, up to 4.1 GHz)",
                "Memory & Storage:4GB, 4Gx1, DDR4, 2666MHz | 256GB M.2 PCIe NVMe Solid State Drive",
                "Display:15.6-inch FHD (1920 x 1080) Anti-glare LED Backlight Narrow Border WVA Display",
                "Graphics:Intel UHD Graphics with shared graphics memory",
                "Operating System & Software:Windows 10 Home Single Language | Microsoft Office Home and Student 2019"],
            "description": "none",
            "rating": "3.5",
            "category": "electronics",
            "image": "https://m.media-amazon.com/images/I/51jPUwqQTFL._SL1000_.jpg",
            "qty": 1
        }]
    },

    {
        "product_param": "women-clothes",
        "product_data": [{
            "id": 61,
            "title": "Leriya Fashion Offers All Kinds of Tops for Both Women and Girls - Tops for Women",
            "price": "399",
            "features": ["Care Instructions: Hand Wash Only",
                "Fit Type: regular fit",
                "There might be minor color variation between actual product and image shown on screen due to lighting on the photography"],
            "description": "none",
            "rating": "3.4",
            "category": "women's clothing",
            "image": "https://m.media-amazon.com/images/I/61A4bKSgm4L._UL1500_.jpg",
            "qty": 1
        },
        {
            "id": 62,
            "title": "C.Cozami Women's Casual Long Sleeves Double Pocket Rayon Shirts",
            "price": "549",
            "features": ["Care Instructions: Hand Wash Only",
                "Fit Type: Regular Fit",
                "Wash Care: Hand Wash Only",
                "Fabric Type: Rayon",
                "Pattern name: Solid",
                "Closure Type: Buttoned",
                "Sleeve Type: Long Sleeve; Collar Style: Spread"],
            "description": "none",
            "rating": "3.6",
            "category": "women's clothing",
            "image": "https://m.media-amazon.com/images/I/71eFrujnUFL._UL1500_.jpg",
            "qty": 1
        },
        {
            "id": 63,
            "title": "Nakoda Creation Women's Plain Slim fit Shirt",
            "price": "574",
            "features": ["Care Instructions: Hand Wash Only",
                "Fit Type: regular fit",
                "Color Name: Black",
                "100% Rayon",
                "hand wash",
                "Button Down",
                "Three Quarter Sleeve",
                "V-neck",
                "Material: 100% rayon, style: casual top, color: black ; This trendy top is crafted for comfort and style",
                "Team it with a pair of jeggings and flats to step out in style",
                " Machine wash, wash separately in cold water, do not bleach, dry in shade, medium iron"],
            "description": "none",
            "rating": "3.5",
            "category": "women's clothing",
            "image": "https://m.media-amazon.com/images/I/415UOryRs-L.jpg",
            "qty": 1
        },
        {
            "id": 64,
            "title": "NIFTY Women's Jeans",
            "price": "711",
            "features": ["Material: 70.5% Cotton,27.5% Poly, 2% Spandex",
                "Mid Rise",
                "Stretchable",
                "Inseam Length: 27 inches",
                "Machine wash cold"],
            "description": "none",
            "rating": "3.9",
            "category": "women's clothing",
            "image": "https://m.media-amazon.com/images/I/61GKdmDLfbL._UL1500_.jpg",
            "qty": 1
        },
        {
            "id": 65,
            "title": "Sugr by Unlimited Women's Skinny Fit Jeans",
            "price": "798",
            "features": ["Care Instructions: Machine Wash",
                "Fit Type: Skinny Fit",
                "Color Name: Black",
                "100% Rayon",
                "Machine wash",
                "Skinny fit",
                "Regular-rise",
                "Inseam Length: 30 inches"],
            "description": "none",
            "rating": "3.7",
            "category": "women's clothing",
            "image": "https://m.media-amazon.com/images/I/61DXMq4vlIL._UL1500_.jpg",
            "qty": 1
        },
        {
            "id": 66,
            "title": "SLVETE Women's Slim Fit Jeans",
            "price": "799",
            "features": ["Fit Type: Slim",
                "Material- 73% Cotton, 25.5% Poly, 2% Spandex",
                "Fit type - Slim Fit",
                "High Rise",
                "Zip Fly with Button closure",
                "Machine wash warm, wash dark colors separately, do not bleach, tumble dry low, warm iron"],
            "description": "none",
            "rating": "4.0",
            "category": "women's clothing",
            "image": "https://m.media-amazon.com/images/I/71aV1wTLjCL._UL1500_.jpg",
            "qty": 1
        },
        {
            "id": 67,
            "title": "GoSriKi Women's Ruby Cotton Printed Straight Kurta with Palazzos & Dupatta",
            "price": "699",
            "features": ["Care Instructions: Dry Clean Only",
                "Fit Type: Regular",
                "This three piece set includes kurta, Palazzos and dupatta.",
                "Style: Straight || Length: Calf Length || Sleeves: 3/4",
                "Fabric : Ruby Cotton",
                "Ocassion: Traditional wear, Casual Wear, party wear, evening wear",
                "Product Color May Slightly Vary Due To Photographic Lighting Sources Or Your Monitor Settings"],
            "description": "none",
            "rating": "3.9",
            "category": "women's clothing",
            "image": "https://m.media-amazon.com/images/I/51TQ5JLU7JS._UL1280_.jpg",
            "qty": 1
        },
        {
            "id": 68,
            "title": "Rajnandini Women's Grey Chanderi Silk Embroidered Semi-Stitched Salwar Suit Material With Printed Dupatta (Free Size)",
            "price": "699",
            "features": ["Care Instructions: Dry clean only",
                "Fabric Detail :: Top - Chanderi Silk, Bottom - Cotton , Dupatta - Nazmin , Inner - Not Available",
                "Color :: Top - Grey , Bottom - Grey , Dupatta - Grey",
                "Top Size : 2.2 Mtr , Top Length : 42 Inches , Bottom Size : 2.25 Mtr , Dupatta Size : 2.2 Mtr , Work : Embroidered ,Work Type : Dori Embroidery , Product Type : Semi-Stitched.",
                "Package Contains : 1 Top || 1 Bottom || 1 Dupatta"],
            "description": "none",
            "rating": "3.6",
            "category": "women's clothing",
            "image": "https://m.media-amazon.com/images/I/81npdOYMaFL._UL1500_.jpg",
            "qty": 1
        },
        {
            "id": 69,
            "title": "Oomph! Women's Unstitched Georgette Salwar Suit Dupatta Material - Navy Blue",
            "price": "359",
            "features": ["Care Instructions: Machine wash",
                "Printed georgette top with printed georgette patiyala bottom fabric. Printed Chiffon dupatta.",
                "Unstitched Kurta Length: 2.1 meters Kurta Width: 42 inch Unstitched Salwar Length: 2.3 meters Salwar Width: 42 inch Dupatta Length: 2.1 meters Dupatta Width: 42 inch",
                "This straight fit dress is ideal for casual wear, party wear, daily wear, office wear as well as festive occasional wear",
                "Wear this salwar suit with statement rings and stud earrings to get the ultimate elegant and simple look"],
            "description": "none",
            "rating": "3.6",
            "category": "women's clothing",
            "image": "https://m.media-amazon.com/images/I/81gqxmtORnL._UL1500_.jpg",
            "qty": 1
        },
        {
            "id": 70,
            "title": "Divine International Trading CoWomen's Georgette Salwar Suit",
            "price": "1,529",
            "features": ["Care Instructions: Machine Wash",
                "Style : Anarkali",
                "Fabric : Faux Georgette , Inner : Santoon",
                "Sleeve Type: Long Sleeve",
                "Free Size (Un-Stitched Up To 44 Inch Bust Size)",
                "Care Instructions: Hand Wash , Machine Wash"],
            "description": "none",
            "rating": "3.6",
            "category": "women's clothing",
            "image": "https://m.media-amazon.com/images/I/717sUlhbPRL._UL1500_.jpg",
            "qty": 1
        }]
    },

    {
        "product_param": "books",
        "product_data": [{
            "id": 71,
            "title": "The Psychology of Money",
            "price": "253",
            "features": [],
            "description": "Timeless lessons on wealth, greed, and happiness doing well with money isn’t necessarily about what you know. It’s about how you behave. And behavior is hard to teach, even to really smart people. How to manage money, invest it, and make business decisions are typically considered to involve a lot of mathematical calculations, where data and formulae tell us exactly what to do. But in the real world, people don’t make financial decisions on a spreadsheet. They make them at the dinner table, or in a meeting room, where personal history, your unique view of the world, ego, pride, marketing, and odd incentives are scrambled together. In the psychology of money, the author shares 19 short stories exploring the strange ways people think about money and teaches you how to make better sense of one of life’s most important matters",
            "rating": "4.6",
            "category": "Books",
            "image": "https://images-na.ssl-images-amazon.com/images/I/41cWqh0OeQL._SX321_BO1,204,203,200_.jpg",
            "qty": 1
        },
        {
            "id": 72,
            "title": "The Snowball: Warren Buffett and the Business of Life",
            "price": "550",
            "features": [],
            "description": "Recounting the life and times of one of the most respected men in the world, The Snowball is the most fascinating financial success story of our time. Warren Buffett, the legendary Omaha investor has never written a memoir, but finally has given Alice Schroeder unprecedented access to him and all those closest to his work, opinions, struggles, triumphs, follies and wisdom. The result is this personally revealing and complete biography of ‘The Oracle of Omaha'. Fully revised and updated with two new chapters on Buffett and the credit crunch, The Snowball is indispensable reading for those who wish to know the man behind the outstanding achievements.",
            "rating": "4.5",
            "category": "Books",
            "image": "https://images-na.ssl-images-amazon.com/images/I/51ZMMZ85dYL._SX327_BO1,204,203,200_.jpg",
            "qty": 1
        },
        {
            "id": 73,
            "title": "Business Adventures",
            "price": "350",
            "features": [],
            "description": "What do the $350 million Ford Motor Company disaster known as the Edsel, the fast and incredible rise of Xerox, and the unbelievable scandals at General Electric and Texas Gulf Sulphur have in common? Each is an example of how an iconic company was defined by a particular moment of fame or notoriety. These notable and fascinating accounts are as relevant today to understanding the intricacies of corporate life as they were when the events happened. Stories about Wall Street are infused with drama and adventure and reveal the machinations and volatile nature of the world of finance. John Brooks's insightful reportage is so full of personality and critical detail that whether he is looking at the astounding market crash of 1962, the collapse of a well‐known brokerage firm, or the bold attempt by American bankers to save the British pound, one gets the sense that history really does repeat itself. This business classic written by longtime New Yorker contributor John Brooks is an insightful and engaging look into corporate and financial life in America.",
            "rating": "4.4",
            "category": "Books",
            "image": "https://images-na.ssl-images-amazon.com/images/I/417P0WhFZrL._SX327_BO1,204,203,200_.jpg",
            "qty": 1
        },
        {
            "id": 74,
            "title": "Corporate Chanakya, 10th Anniversary Edition-2021: Successful Management the Chanakya Way",
            "price": "229",
            "features": [],
            "description": "A pioneer of economics and political science in India, Chanakya was one of the most brilliant, tactful and shrewd economists and strategists of the Mauryan Era. Building the entire Mauryan Empire can be attributed to Chanakya's witty principles and out of the box strategies. The modern day world is a witness to innumerable business empires which need effective management to remain at par with growing competition. The author makes use of the aphorisms or sutras proposed in Chanakya's book called Arthasastra (Economics), in the management and functioning of modern day businesses.",
            "rating": "4.4",
            "category": "Books",
            "image": "https://images-na.ssl-images-amazon.com/images/I/416ZmY24ORL._SX323_BO1,204,203,200_.jpg",
            "qty": 1
        },
        {
            "id": 75,
            "title": "The 5 AM Club: Own Your Morning, Elevate Your Life ",
            "price": "231",
            "features": [],
            "description": "Part manifesto for mastery, part playbook for genius-grade productivity and part companion for a life lived beautifully, the 5 am club is a work that will transform your life. Forever.Legendary leadership and elite performance expert Robin Sharma introduced The 5 AM Club concept over twenty years ago, based on a revolutionary morning routine that has helped his clients maximize their productivity, activate their best health and bulletproof their serenity in this age of overwhelming complexity.",
            "rating": "4.5",
            "category": "Books",
            "image": "https://images-na.ssl-images-amazon.com/images/I/41MC15v6UIL._SX332_BO1,204,203,200_.jpg",
            "qty": 1
        },
        {
            "id": 76,
            "title": "The Intelligent Investor",
            "price": "479",
            "features": [],
            "description": "It is a widely acclaimed book by Benjamin Graham on value investing. Written by one of the greatest investment advisers of twentieth century, the book aims at preventing potential investors from substantial errors and also teaches them strategies to achieve long-term investment goals.Over the years, investment market has been following teachings and strategies of Graham for growth and development. In the book, Graham has explained various principles and strategies for investing safely and successfully without taking bigger risks. Modern-day investors still continue to use his proven and well-executed techniques for value investment.",
            "rating": "4.5",
            "category": "Books",
            "image": "https://images-na.ssl-images-amazon.com/images/I/51DLoxAJ68L._SX324_BO1,204,203,200_.jpg",
            "qty": 1
        },
        {
            "id": 77,
            "title": "Rich Dad Poor Dad: What the Rich Teach Their Kids About Money That the Poor and Middle Class Do Not!",
            "price": "317",
            "features": [],
            "description": "It's been nearly 25 years since Robert Kiyosaki’s Rich Dad Poor Dad first made waves in the Personal Finance arena.It has since become the #1 Personal Finance book of all time... translated into dozens of languages and sold around the world.Rich Dad Poor Dad is Robert's story of growing up with two dads — his real father and the father of his best friend, his rich dad — and the ways in which both men shaped his thoughts about money and investing. The book explodes the myth that you need to earn a high income to be rich and explains the difference between working for money and having your money work for you.",
            "rating": "4.6",
            "category": "Books",
            "image": "https://images-na.ssl-images-amazon.com/images/I/51wOOMQ+F3L._SX312_BO1,204,203,200_.jpg",
            "qty": 1
        },
        {
            "id": 78,
            "title": "The Business School",
            "price": "145",
            "features": [],
            "description": "The Business School is a popular book written by Robert T. Kiyosaki. From this book the reader will get know all information of Multi-level marketing. He explains beautifully why Multi- level-marketing is important.Multi-level marketing is a marketing approach in which the sales strength is repaid not only for sales they produce, but also for the sales of the other salespersons that they hire. This hired sales force is mentioned as the participant's 'downline' and can offer multiple levels of return.",
            "rating": "4.5",
            "category": "Books",
            "image": "https://images-na.ssl-images-amazon.com/images/I/51cPGZV7v9L._SX318_BO1,204,203,200_.jpg",
            "qty": 1
        },
        {
            "id": 79,
            "title": "Let's Build A Company: A Start-up Story Minus the Bullshit",
            "price": "192",
            "features": [],
            "description": "Harpreet Grover and Vibhore Goyal met in college and then spent the next decade of their lives building a company before exiting successfully.One way to tell their story is this: they had a dream, they followed it and, then, through perseverance, they made it come true.But that's not really the truth. Like everything in life-at least everything worth having-it wasn't that simple. There was blood, sweat and tears, there was loss of capital, loss of friendship and even a loss of faith along the way.",
            "rating": "4.5",
            "category": "Books",
            "image": "https://images-eu.ssl-images-amazon.com/images/I/41IyVy1bIiS._SY264_BO1,204,203,200_QL40_FMwebp_.jpg",
            "qty": 1
        },
        {
            "id": 80,
            "title": "The Money Matters",
            "price": "250",
            "features": [],
            "description": "Attaining financial freedom is like giving birth to a child, which cannot happen with single-person efforts. You and your spouse both need to make up their minds 'yes, we want to be financially free'. When a couple planned to become parents, they have to change many things, from their daily routines to their habits, from their spending choices to their eating habits. The financial freedom journey is also the same. To achieve financial freedom, you and your spouse need to be determinant and may be changed some or many habits. You need to create a free space in your earnings and clean-up all the financial messes. You give me the desired commitment, and I will show you the path which leads you to the new world where you are free of all financial worries. I know it will not be a comfortable ride, but your future road will be as smooth as an expressway after some bouncy patches. In this book, we discuss different steps which are essential for your journey. We discuss from determination to portfolio creation. We learn some simple techniques to achieve your goals. We create a new space for your new child, 'financial freedom'. Best of luck",
            "rating": "4.5",
            "category": "Books",
            "image": "https://images-eu.ssl-images-amazon.com/images/I/51qad-nbHiL._SY264_BO1,204,203,200_QL40_FMwebp_.jpg",
            "qty": 1
        },
        {
            "id": 81,
            "title": "The Millionaire Fastlane: Crack the Code to Wealth and Live Rich for a Lifetime",
            "price": "379",
            "features": [],
            "description": "There is a Fastlane to making millions, a shortcut paved by Mathematics, were you can live rich now, versus dying rich later! Mainstream financial gurus hoodwink you into believing that wealth can be created by recklessly trusting in the uncontrollable and unpredictable markets: the stock market, The job market, and the housing market. They propagate a dream-stealing, soul-sucking dogma known as “get rich slow”, which dubiously promises “wealth-in-a-wheelchair”―leading you to sacrifice your youth for a financial plan that reaps dividends only in life’s Twilight.",
            "rating": "4.6",
            "category": "Books",
            "image": "https://images-eu.ssl-images-amazon.com/images/I/51uLw8zJH3L._SY264_BO1,204,203,200_QL40_FMwebp_.jpg",
            "qty": 1
        },
        {
            "id": 82,
            "title": "The Richest Man in Babylon",
            "price": "129",
            "features": [],
            "description": "If you are looking for some financial wisdom, this book is the perfect pick and holds the key to simple and efficient financial planning. It guides you to the secret to acquiring, keeping and making money as per the principles of Babylon. The Richest Man in Babylon explains simple laws of making money along with time tested principles that help you gain personal wealth. Right from the importance of saving to understanding common mistakes people make with money, the book will come in handy with effective tips to build wealth. People have been using this book as a financial guide over decades. Over a million copies have been sold so far and the book continues to be one of the few bestselling financial books that really work!",
            "rating": "4.5",
            "category": "Books",
            "image": "https://images-eu.ssl-images-amazon.com/images/I/41e2zqOvw0L._SY264_BO1,204,203,200_QL40_FMwebp_.jpg",
            "qty": 1
        }]
    },

    {
        "product_param": "kitchen",
        "product_data": [{
            "id": 83,
            "title": "SWARG Non-Slip Wooden Bamboo Cutting Board with Antibacterial Surface & Stainless Steel  Handle, Chopping Cutting Board for Kitchen",
            "price": "649",
            "features": ["MASTER CHEF QUALITY - Ultra strong, attractive, versatile, durable and lightweight construction made from compressed high quality bamboo. Moisture resistant, anti-microbial bamboo effectively prevents warps, splints, or breaks, and also is easy to clean and maintain. Won’t dull knife edges.",
                "WITH JUICE GROOVE AND ROUNDED CORNER – Drip groove provides protection against running juices when cutting meats and other food products. Edges are rounded with a smooth finish to make sure your hands are safe when moving.",
                "EASY PREP ON LARGE CUTTING & CHOPPING BOARD - Great For Bread, Vegetables (Carrots, Onions, Mushrooms, Cabbage And More) Salads (Lettuce, Tomatoes, Radishes, Peppers And Celery To Name A Few), Fruits (Watermelon, Apples, Oranges & Strawberries) and Meats (Fish, Steak, Beef, Chicken, Pork).",
                "DUAL PURPOSE - CUTTING BOARD AND SERVING TRAY - You can use the grooved side for cutting things, and the un-grooved flat surface on the other to cutting breads, pastries and serving cheese and crackers, etc.",
                "EASY TO STORE & CLEAN - A finger hole in the bamboo chopping board makes it easy to grip and carry around. It also makes it easy to hang the chopping board on wall hooks. Cleaning the bamboo chopping board is easy with soap and water. Strong antimicrobial construction does not allow moisture to absorb into the wood."],
            "description": "none",
            "rating": "5.0",
            "category": "kitchen",
            "image": "https://m.media-amazon.com/images/I/715YvQK7CbL._AC_UL320_.jpg",
            "qty": 1
        },
        {
            "id": 84,
            "title": "KITOME Plastic Self Draining Tableware Storage Box - Spoon, Knife, Fork, Chopstick, Cutlery Holder/Organizer Stand for Kitchen, Dining Table (White)",
            "price": "549",
            "features": ["Our utensil caddy is an essential tool in the kitchen. It can neatly organize your tableware. For example, you can store chopsticks, forks and spoons. Your kitchen will not be messy again.",
                "This flatware organizer is detachable, and the oak base has three card slots, so you can securely place the cutlery in the card slot. The oak base also has black anti-slip buttons for added safety during use. There are several outlet holes at the bottom of the holders, which is convenient to drainage. It has three cylinders, each with a pattern of spoons, forks and chopsticks. (Cleaning Brush Included ).",
                "Measures 9.2 inch X 3.3 inch X 5.1 inches. The diameter of the cylinder is 2.5 inch. With an oak base, you can easily bring the cutlery to the table during a family dinner.",
                "In order to provide a better product, the base is made of oak and the utensil holder is made of high quality plastic, which makes our flatware caddy more durable. It looks beautiful too.",
                "NOTE : Spoons, Forks & Chopsticks are shown in pictures are not included."],
            "description": "none",
            "rating": "4.3",
            "category": "kitchen",
            "image": "https://m.media-amazon.com/images/I/51ktpyaQOKL._AC_UL320_.jpg",
            "qty": 1
        },
        {
            "id": 85,
            "title": "Meyer Pre Seasoned Cast Iron Deep Kadai (20 cm, Black)",
            "price": "2,850",
            "features": ["Hassle free LIFETIME WARRANTY",
                "Totally Toxin-free – No ENAMEL, No CHEMICAL coating on any side. Pre-seasoned with 100% Vegetable Oil",
                " Uni-body ‘one-piece’ design – free of any screws or weld joints. Has a Shatter Resistant Tempered Glass Lid",
                " Adds a STRONG AUTHENTIC INDIAN FLAVOUR to your preparations. SAVES COOKING GAS – High-quality cast material heats quickly, evenly & retains heat longer",
                " Suitable for all cooktops including Induction. Comes with two canvas grips for easy handling",],
            "description": "none",
            "rating": "4.1",
            "category": "kitchen",
            "image": "https://m.media-amazon.com/images/I/51h9mGAT-vS._AC_UL320_.jpg",
            "qty": 1
        },
        {
            "id": 86,
            "title": "GLUN Waterproof Unisex Kitchen Apron Checkered Design with Roomy Centre Pocket With Extra Long Waist Strap Pack Of 3 Different Colors",
            "price": "169",
            "features": ["Made In India",
                "Hand & Machine Washable.",
                "Full-Size Apron Fit For Everyone. the fabric is soft in feel and durable to last long.",
                "Our Designers stitch your garment to perfection.",
                "Ideal for Men and Women."],
            "description": "none",
            "rating": "3.5",
            "category": "kitchen",
            "image": "https://m.media-amazon.com/images/I/81S2g58MNTL._AC_UL320_.jpg",
            "qty": 1
        },
        {
            "id": 87,
            "title": "CR18 COLLECTION Stainless Steel Kitchen Rack, Kitchen Organizer and Space Saver, Counter top Stainless Steel Kitchen Stand 2-Tier Trolley Basket for Boxes Utensils Dishes Plates for Home",
            "price": "499",
            "features": ["MULTIPURPOSE : trolley can be used for multi purposes, like storing fruits and vegetables,keeping books,or any other cosmetic items or cookware items and house products!",
                "MATERIAL: Constructed of durable steel with a gleaming chrome finish, the stylish two-shelf shelving unit offers the best of both rugged reliability and modern appeal!",
                "SMART STORAGE: Use anywhere you need to keep food, pantry and kitchen items organized; Perfect for organizing pasta, packets, extra supplies of salt, dressing and vinegar, macaroni and cheese boxes, baking supplies, condiments and more; These bins also work in any room of your home!",
                "FUNCTIONAL & VERSATILE: The perfect solution for organizing a multitude of items - such as video games, bath soaps, shampoos, conditioners, linens, towels, laundry needs, craft supplies and more; Use in bathroom, bedroom, closet, laundry room, utility room, garage, hobby and craft room, home office, mudroom and entryways; Perfect for homes, apartments, condos, college dorm rooms, RVs and campers",
                "2 SHELVES : This trolley has 2 shelves, which makes it large enough to store many things at a time!"],
            "description": "none",
            "rating": "3.9",
            "category": "kitchen",
            "image": "https://m.media-amazon.com/images/I/51zMm+bAvRS._AC_UL320_.jpg",
            "qty": 1
        },
        {
            "id": 88,
            "title": "homez store DEEP Fry 6 NO, Steel Grey",
            "price": "299",
            "features": ["100% STAINLESS STEEL, RUST RESISTANT, 100 % FOOD GRADE, ISO CERTIFIED. DISHWASHER SAFE, EASY TO CLEAN AND WASH",
                "Number of pieces: 1.0",
                "Included components: ONLY PRODUCT",
                "item weight: 150.0 grams"],
            "description": "none",
            "rating": "3.5",
            "category": "kitchen",
            "image": "https://m.media-amazon.com/images/I/71YbH8fZvgL._AC_UL320_.jpg",
            "qty": 1
        },
        {
            "id": 89,
            "title": "Shopme store CR18 Collection Big Size Kitchens Stainless Steel V Shape Cup Stand Pieces Coffee & Tea Mug Holder | 12 Hooks for Cups & Mugs (Color: Silver, 12 Cups Stand)",
            "price": "275",
            "features": ["This cup stand can carry 12 cup at once.",
                "Very good looking product for dining table and kitchen.100% Rust and corrosion free .fit in small area",
                "made from high and heavy steel quality stainless steel",
                "weight 450g ,Dimension 14.6x5.5 Inch",
                "Product Color - Shining Silver Color ; Long Service Life , Simple Design , High Efficiency , Enhanced Durability , Crack Resistance"],
            "description": "none",
            "rating": "4.3",
            "category": "kitchen",
            "image": "https://m.media-amazon.com/images/I/719MWKHQnJL._AC_UL320_.jpg",
            "qty": 1
        },
        {
            "id": 90,
            "title": "shreeji Home & Kitchen Care 3 in 1 Plastic Kitchen Dish Drainer Drying Rack Water Drip Washing Space Saver Storage Organiser Basket Utensils Tools Cutlery Stand Organizer | Color-Sky Brown",
            "price": "375",
            "features": ["Made In India'3 in 1 Plastic Kitchen Water Drip Dish Drainer Drying Storage Rack Space SaverMade In India'3 in 1 Plastic Kitchen Water Drip Dish Drainer Drying Storage Rack Space Saver",
                "lMade using high-quality, durable plasticMade using high-quality, durable plastic Made using high-quality, durable plastic",
                "Consists of a storage basket for storing and arranging just washed utensils",
                "Provision of a slanting surface at the bottom for quick water drainage from washed utensils into the sink, keeping the kitchen clean and dry"],
            "description": "none",
            "rating": "4.1",
            "category": "kitchen",
            "image": "https://m.media-amazon.com/images/I/61iiWyaMjNS._AC_UL320_.jpg",
            "qty": 1
        },
        {
            "id": 91,
            "title": "Kariox Stainless Steel Multipurpose Kitchen Corner Shelf Rack Stand/Chakla Belan Storage (30 * 30 * 30 cm) (Set of 1)",
            "price": "549",
            "features": ["NO INSTALLATION REQUIRED: This kitchen organizer can be free standing, no installation required",
                "MATERIAL: Made up of high quality stainless steel with a beautiful chrome finish! It is 100% Rust free!",
                "SMART DESIGN: Boost your kitchen cupboard storage quickly and easily with this three-tier corner plate rack. It maximises the vertical space in any cupboard, counter or under sink area with a large surface area suitable for plates of all sizes and other kitchen essentials. Crafted from robust stainless steel with a sleek chrome finish. It is 100% rust free!",
                "SPACE SAVER: This plate shelf storage rack is designed to fit the majority of kitchen cupboards for an easy way to increase storage space",
                "STRONG AND STURDY: It is highly strong and sturdy! Can accomodate weights of stainless steels plates and dishes very easily and other steel or other metal utensils!"],
            "description": "none",
            "rating": "5.0",
            "category": "kitchen",
            "image": "https://m.media-amazon.com/images/I/61r-3l9cMhS._AC_UL320_.jpg",
            "qty": 1
        },
        {
            "id": 92,
            "title": "Ardith Handy and Compact Chopper XL 500ml with 3 Blades and Whisker for effortlessly Chopping Vegetables and Fruits for Your Kitchen (500ml)",
            "price": "299",
            "features": ["POWERFUL & VERSATILE:- Perfect for chopping onion;garlic;vegetables;nuts;herbs;veggies;pesto;hummus;salsa;guacamole;boneless meat;making baby food;salsa;salad and many more. The number of pulls controls how finely the food is chopped.",
                "CONVENIENT & SAFE:- Makes food preparation fun and easy. Just pull the cord a few times to chop/mince your ingredients. Great for small kitchens;RVs;travel and camping. Made from Food Grade;BPA-free material;no hazard for your health.",
                "DESIGNED FOR PERFECT:- Features sharp stainless steel blades for fast chopping;comfort soft grip lid;easy pull cord;large handle;anti-skid base for easy leverage. An essential tool for a busy kitchen;and one of the secrets to making consistent quality meals.",
                "LEAK-PROOF STORAGE LID:- A storage lid is included to keep chopped food fresh in the refrigerator. So you can even use as a storage container.",
                "EASY TO CLEAN:- Blades, Bowl and Storage Lid are Top-Rank Dishwasher Safe. They can be Disassembled Easily for Quick Clean."],
            "description": "none",
            "rating": "4.9",
            "category": "kitchen",
            "image": "https://m.media-amazon.com/images/I/515wyJ-l8FL._AC_UL320_.jpg",
            "qty": 1
        }]
    },

    {
        "product_param": "women-shoes",
        "product_data": [{
            "id": 93,
            "title": "ASIAN Multicolor Walking Shoes,Running Shoes,Casual Shoes,Canvas Shoes,Sneakers,Loafers Combo Pack of 2 for Women",
            "price": "549",
            "features": ["Sole: Polyvinyl Chloride",
                "Closure: Lace-Up",
                "Heel Height: 1 inches",
                "Shoe Width: Medium",
                "Upper Features: New, Breathable canvas upper which is easily washable, perfect for all seasons - winter, summer and rainy, designed to give you the most comfortable fitting. These are quick drying washable shoes which makes it easy for consumers to wash and sanitize them easily."],
            "description": "none",
            "rating": "3.7",
            "category": "women shoe",
            "image": "https://m.media-amazon.com/images/I/719z2zRUzPL._AC_UL320_.jpg",
            "qty": 1
        },
        {
            "id": 94,
            "title": "Santo Collection Casual Sparkling Shoes for Women",
            "price": "399",
            "features": ["Sole: Thermoplastic Rubber",
                "Closure: Slip On",
                "Shoe Width: Medium",
                "Sparkling Partywear shoe",
                "Sparkling Partywear Sandal",
                "Fashionable ensemble perfectly without compromising your comfort",
                "These sandals will provide your feet with maximum flexibility and comfort and will also be highly durable for women",
                "Occasion: Wedding, Party wear, Casual, ethnic & other festival"],
            "description": "none",
            "rating": "5.0",
            "category": "women shoe",
            "image": "https://m.media-amazon.com/images/I/91fUzAsF73S._AC_UL320_.jpg",
            "qty": 1
        },
        {
            "id": 95,
            "title": "Sparx Women's Sx0123l Sneakers",
            "price": "915",
            "features": ["Closure: Pull On",
                "Shoe Width: Regular",
                "Outer Material: Mesh",
                "Closure Type: Slip On",
                "Heel type: flats",
                "Toe Style: Round Toe",
                "Warranty Type: Manufacturer",
                "Warranty Description: 30 days"],
            "description": "none",
            "rating": "4.3",
            "category": "women shoe",
            "image": "https://m.media-amazon.com/images/I/81APHaJpiUL._AC_UL320_.jpg",
            "qty": 1
        },
        {
            "id": 96,
            "title": "shoexpress Women's Myx-s1 Walking Shoes",
            "price": "1283",
            "features": ["Closure: Slip-On",
                "Shoe Width: Medium",
                "Color: Pink",
                "Outer Material: Textile",
                "Closure: Slip-on",
                "Package Contents: 1 Pair of Walking Shoes"],
            "description": "none",
            "rating": "4.5",
            "category": "women shoe",
            "image": "https://m.media-amazon.com/images/I/51DXWUfoKrL._AC_UL320_.jpg",
            "qty": 1
        },
        {
            "id": 97,
            "title": "ZAPATOZ Women's Black Textile Slip-On Lightweight Running Walking Shoes",
            "price": "499",
            "features": ["Sole: Polyvinyl Chloride",
                "Closure: Pull On",
                "Shoe Width: Medium",
                "Material: Textile",
                "Stylish and Comfortable Shoes for both Casual & Party Wear. These Trendy Shoes go well with Dresses, Shorts, Skirts.",
                "Comfortable sole: Extremely light sole and upper material for all day comfort."],
            "description": "none",
            "rating": "3.8",
            "category": "women shoe",
            "image": "https://m.media-amazon.com/images/I/61glP+vuh-L._AC_UL320_.jpg",
            "qty": 1
        },
        {
            "id": 98,
            "title": "ASIAN Women's Running Shoe",
            "price": "999",
            "features": ["Sole: EVA",
                "Closure: Pull On",
                "Shoe Width: Medium",
                "Material: Mesh",
                "Sole Material: Eva",
                "Closure: Slip-On",
                "Lifestyle: Sports",
                "Care Instructions: Wipe with a clean, dry cloth when needed Do not wash with detergent or in washing machine"],
            "description": "none",
            "rating": "4.0",
            "category": "women shoe",
            "image": "https://m.media-amazon.com/images/I/61Kk8qMByuL._AC_UL320_.jpg",
            "qty": 1
        },
        {
            "id": 99,
            "title": "Aura Women Sky Blue Canvas Casual Shoes - UK 7",
            "price": "315",
            "features": ["Closure: lace-up",
                "Durable and Comfortable",
                "Upper Material: Canvas",
                "Ideal for: Women",
                "Package Contains: 6 Pair of Casual Shoes Surface Dirt Can Be Cleaned With A Good Quality Brush Or A Damp Cloth."],
            "description": "none",
            "rating": "3.0",
            "category": "women shoe",
            "image": "https://m.media-amazon.com/images/I/71RSashs3eL._AC_UL320_.jpg",
            "qty": 1
        },
        {
            "id": 100,
            "title": "Yahe Women's Bellies",
            "price": "499",
            "features": ["Sole: Rubber",
                "Closure: Pull On",
                "Shoe Width: Medium",
                "Colour - blue",
                "Material: faux leather",
                "Occasion: casual"],
            "description": "none",
            "rating": "3.8",
            "category": "women shoe",
            "image": "https://m.media-amazon.com/images/I/71WIMvcHb6S._AC_UL320_.jpg",
            "qty": 1
        },
        {
            "id": 101,
            "title": "BATA Women's Mesh Ballet Flat",
            "price": "599",
            "features": ["Closure: Pull-On",
                "Shoe Width: Medium",
                "Comfortable shoes",
                "Target gender: female",
                "closure type: Slip-On",
                "item weight: 1000.0 grams"],
            "description": "none",
            "rating": "4.1",
            "category": "women shoe",
            "image": "https://m.media-amazon.com/images/I/611fHwHNGOS._AC_UL320_.jpg",
            "qty": 1
        },
        {
            "id": 102,
            "title": "BATA Women's Sepia Sneakers",
            "price": "499",
            "features": ["Closure: Pull On",
                "Shoe Width: Regular",
                "Outer Material: Canvas",
                "Closure Type: Slip On",
                "Toe Style: Round Toe",
                "Warranty Type: Manufacturer",
                "Warranty Description: 90 days"],
            "description": "none",
            "rating": "4.1",
            "category": "women shoe",
            "image": "https://m.media-amazon.com/images/I/81t5VTbw6VL._AC_UL320_.jpg",
            "qty": 1
        }]
    }
]